### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by Frostist** [Siyavula/siyavula-moodle-question#26]
Hi guys!

Is there a guide on how to get this plugin working? 

Thanks

**Comment by marknewlyn** [comment]
Hi @Frostist 

Yes, this is the work-in-progress guide: https://docs.google.com/document/d/1x4P93j-2ih13XnoxaLqMY7_VvlxNbnWd9RZzQ10APA0/edit?usp=sharing

Cheers

Mark
